cineflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('create_profile/', views.CreateProfile.as_view(), name='create_profile'),
    path('profile/<int:pk>/update/', views.UpdateProfile.as_view(), name='update_profile'),
    path('search/', views.search, name='search'),
    path('top_movies/', views.top_movies, name='top_movies'),
    path('coming_soon/', views.coming_soon, name='coming_soon'),
    path('movie/<movie_id>/', views.movie_details, name='details'),
    path('movie/<movie_id>/add_review/', views.add_review, name='add_review'),
    path('movie/<movie_id>/delete_review/<int:pk>/', views.DeleteReview.as_view(), name='delete_review'),
    path('profile/<int:profile_id>/assoc_favorites/<int:movie_id>/', views.assoc_favorites, name='assoc_favorites'),
    path('profile/<int:profile_id>/unassoc_favorites/<int:movie_id>/', views.unassoc_favorites, name='unassoc_favorites'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Movie(models.Model):
    imdbId = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    year = models.CharField(max_length=100)
    image = models.CharField(max_length=250)
    genres = models.CharField(max_length=200, null=True)
    awards = models.CharField(max_length=300, null=True)
    trailer = models.CharField(max_length=300, null=True)

    def __str__(self):
        return f'{self.title} ({self.id})'


class Review(models.Model):
    RATING_CHOICES = (
        ('1', '⭐️'),
        ('2', '⭐️⭐️'),
        ('3', '⭐️⭐️⭐️'),
        ('4', '⭐️⭐️⭐️⭐️'),
        ('5', '⭐️⭐️⭐️⭐️⭐️')
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    movie = models.ForeignKey(
        Movie, 
        on_delete=models.CASCADE
    )
    rating = models.CharField(max_length=2, choices=RATING_CHOICES, blank=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True) 


    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.id})

    def __str__(self):
        return f'Review for: {self.movie.title} ({self.id})'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.CharField(max_length=200, default='https://i.imgur.com/1t8xewY.png')
    bio = models.TextField()
    reviews = models.ManyToManyField(Review)
    movie = models.ManyToManyField(Movie)

    def __str__(self):
        return f'{self.user.username} ({self.id})'

    def get_absolute_url(self):
        return reverse('profile', kwargs={'pk': self.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Review


class ReviewForm(ModelForm):
  class Meta:
    model = Review
    fields = ['body', 'rating']

main_app/views.py
import requests
from django.shortcuts import render, redirect
from main_app.models import Movie
from django.contrib.auth import login
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Profile, Review
from .forms import ReviewForm


def home(request):
    return render(request, 'home.html' )

def search(request):
    all = request.GET.get('all')
    if all:
        response = requests.get(f'https://imdb-api.com/en/API/SearchAll/k_54v7k1ut/{all}').json()
        results = response['results']
        if results:
            for item in results:
                movie_data = Movie(
                    imdbId = item['id'],
                    title = item['title'],
                    image = item['image'],
                    )
                try: 
                    if Movie.objects.get(imdbId=item['id']):
                        pass
                except:
                    movie_data.save()
            return render(request, 'search.html', {'results': results})

def top_movies(request):
    response = requests.get('https://imdb-api.com/en/API/Top250Movies/k_54v7k1ut').json()
    items = response['items'][:50]

    for item in items:
        try: 
            if not Movie.objects.get(imdbId=item['id']):
                imdbId = item['id']
                # response = requests.get(f'https://imdb-api.com/en/API/Title/k_54v7k1ut/{imdbId}').json()
                # vid_response = requests.get(f'https://imdb-api.com/API/Trailer/k_54v7k1ut/{imdbId}').json()
                movie_data = Movie(
                    imdbId = item['id'],
                    title = item['title'],
                    year = item['year'],
                    image = item['image'],
                    genres = item['genres'],
                    # awards = response['awards'],
                    # trailer = vid_response['linkEmbed'],
                )
                movie_data.save()
        except Exception as e:
            print('error', e)

    return render(request, 'top_movies.html', {'all_top_movies': items})

def coming_soon(request):
    response = requests.get('https://imdb-api.com/en/API/ComingSoon/k_54v7k1ut').json()
    items = response['items'][:15]
    
    for item in items:
        try: 
            if not Movie.objects.get(imdbId=item['id']):
                imdbId = item['id']
                # response = requests.get(f'https://imdb-api.com/en/API/Title/k_54v7k1ut/{imdbId}').json()
                # vid_response = requests.get(f'https://imdb-api.com/API/Trailer/k_54v7k1ut/{imdbId}').json()
                movie_data = Movie(
                    imdbId = item['id'],
                    title = item['title'],
                    year = item['year'],
                    image = item['image'],
                    genres = item['genres'],
                    # awards = response['awards'],
                    # trailer = vid_response['linkEmbed'],
                )
                movie_data.save()
        except Exception as e:
            print('error', e)
        
    return render(request, 'coming_soon.html', {'all_coming_soon': items})


def movie_details(request, movie_id):
    response = requests.get(f'https://imdb-api.com/en/API/Title/k_54v7k1ut/{movie_id}').json()
    vid_response = requests.get(f'https://imdb-api.com/API/Trailer/k_54v7k1ut/{movie_id}').json()
    movie_data = Movie(
            imdbId = response['id'],
            title = response['title'],
            year = response['year'],
            image = response['image'],
            genres = response['genres'],
            # awards = response['awards'],
            trailer = vid_response['linkEmbed'],
        )
    try: 
        if Movie.objects.get(imdbId=movie_id):
            pass
    except:
        movie_data.save()
    movie = Movie.objects.get(imdbId=movie_id)
    review_form = ReviewForm()
    return render(request, 'movie/details.html', {'review_form': review_form, 'movie_data': movie, 'response': response, 'vid_response': vid_response})

@login_required
def add_review(request, movie_id):
    form = ReviewForm(request.POST)
    if form.is_valid():
        new_review = form.save(commit=False)
        movie = Movie.objects.get(id=movie_id)
        new_review.movie_id = movie.id
        new_review.user = request.user
        new_review.save()
    return redirect('details', movie_id=movie.imdbId)

class DeleteReview(LoginRequiredMixin, DeleteView):
    model = Review
    def get_success_url(self):
        return f"/movie/{ self.object.movie.imdbId }"


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/create_profile')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

@login_required
def profile(request):
    return render(request, 'users/profile.html')

class CreateProfile(LoginRequiredMixin, CreateView):
    model = Profile
    fields = ['avatar', 'bio']
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class UpdateProfile(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = ['avatar', 'bio']
    success_url = '/profile'
    
@login_required
def assoc_favorites(request, profile_id, movie_id):
    Profile.objects.get(id=profile_id).movie.add(movie_id)
    return redirect('/profile', profile_id=request.user.id)

@login_required
def unassoc_favorites(request, profile_id, movie_id):
    Profile.objects.get(id=profile_id).movie.remove(movie_id)
    return redirect('/profile', profile_id=request.user.id)

main_app/templates/movie/details.html
{% extends 'base.html' %}
{% block content %}

<div class="movie-card">
    <div class="card-left">
        <img src="{{ response.image }}">
    </div>
    <div class="card-right">
      <h1>{{ movie_data.title }}</h1>
      <div class="movie-details">
        <ul>
          <li>{{ response.year }}</li>
          {% if response.runtimeStr %}
          <li>{{ response.runtimeStr }}</li>
          {% else %}
          {% endif %}
          <li>{{ response.genres }}</li>
          {% if user.is_authenticated %}
          <li><form action="{% url 'assoc_favorites' user.profile.id movie_data.id %}" method="POST"></li>
            {% csrf_token %}
            <button type="submit" class="btn">❤️ Add Favorite</button>
          </form>
      {% else %}
        <a href="{% url 'signup' %}"><button class="favorite">❤️ Add Favorite</button></a>
      {% endif %}
        </ul>
        <div class="plot">
          <p>{{ response.plot }}</p>
        </div>
            <iframe src="{{ vid_response.linkEmbed }}?width=480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" frameborder="no" scrolling="no"></iframe>
      </div>
    </div>
  </div>
  
<h1>Similar Movies</h1>
<div class="extra-details">
    {% for items in response.similars|slice:"7" %}
        <a href="{% url 'details' items.id %}">
        <img src="{{ items.image }}">
    {% endfor %}
    </a>
</div>

<h1>Actors</h1>
<div class="extra-details">
    {% for items in response.actorList|slice:"7" %}
        <div class="actor">
            <img src="{{ items.image }}">
            <p class="actor-details">
                {{ items.name }}</br>
                <span class="smaller">{{ items.asCharacter }}</span>
            </p>
        </div>
    {% endfor %}
</div>


<h1>Reviews </h1>
{% for review in movie_data.review_set.all %}<br>
<div class="comment-card">
        <ul>
            <li>{{ review.user.username }}</li>
            <li>{{ review.rating }}/5 ⭐️'s </li>
        </ul>
        <hr>
        <p>{{ review.body }}</p>
        <div class="comment-info">
            Posted: {{ review.created }}
            {% if review.user == request.user %}
                <a href="{% url 'delete_review' movie_data.id review.id %}">&nbsp;🗑️&nbsp;</a>
            {% endif %}
        </div>
    </div>
{% endfor %}

<h1>Leave Your Review</h1>
<div class="comment-form">
    <form action="{% url 'add_review' movie_data.id %}" method="POST">
        {% csrf_token %}
        {{ review_form.as_p }}
        <input type="submit" value="⭐️ Add Review">
    </form>
</div>

{% endblock %}